#!/bin/sh

dir=`dirname $0`

cd $dir/../src

mkdir ../bin 2>/dev/null

echo "const version = '''" > release.dart 
git log -1 --format=%cd origin/main >> release.dart
echo "''';" >> release.dart

dart compile exe run-prover.dart	-o ../bin/run-prover.exe
dart compile exe run-challenger.dart	-o ../bin/run-challenger.exe
