#!/bin/sh

dir=`dirname $0`

while :
do
	if [ ! -z $DISABLE_POB_UPDATES ]
	then
		if [ -e "new--run-pob-challenger.exe" ]
		then
			mv new--run-pob-challenger.exe run-pob-challenger.exe
			chmod +x run-pob-challenger.exe
		fi
	fi

	./run-pob-challenger.exe $1 $2 $3 $4 $5 $6 $7 $8 $9

	echo "================> Restarting ===================="
	sleep 1
done
